### PR TITLE
Tracy 2.6 support

### PR DESCRIPTION
**Pull request by JohnyRicio**

### CODE REVIEW

**Comment by fprochazka** [comment]
Thank you!

**Comment by JohnyRicio** [comment]
You are welcome. Please can you tell me, when will be version released? Thank you.

**Comment by JohnyRicio** [comment]
@jankonas It is up on you. I don't have any problem with lower version. You can send PR with fix.

**Comment by janreges** [comment]
Hi guys,

when will be new version (with Tracy 2.6 support) released? Probably as v1.3.3?

Thank you :)

**Comment by enumag** [comment]
Considering this PR also increased required PHP version it can't be 1.3.3. Personally I'd like to get https://github.com/Kdyby/Monolog/pull/35 solved before the release.

**Pull request closed without merging**
